// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for IntegrationSource.
const (
	Github IntegrationSource = "github"
	Steam  IntegrationSource = "steam"
)

// Defines values for LogState.
const (
	Listed   LogState = "listed"
	Unlisted LogState = "unlisted"
)

// Defines values for MediaState.
const (
	Available MediaState = "available"
	Pending   MediaState = "pending"
)

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Integration defines model for Integration.
type Integration struct {
	// Data Latest polled state; null when nothing has been observed.
	Data *map[string]interface{} `json:"data,omitempty"`

	// FetchedAt When custodian last fetched; present even when data is null.
	FetchedAt time.Time         `json:"fetched_at"`
	Source    IntegrationSource `json:"source"`
}

// IntegrationSource defines model for IntegrationSource.
type IntegrationSource string

// Log defines model for Log.
type Log struct {
	Body        string    `json:"body"`
	CoverImage  *string   `json:"cover_image,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	ReadingTime *int      `json:"reading_time,omitempty"`
	Slug        string    `json:"slug"`
	State       LogState  `json:"state"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// LogCreate defines model for LogCreate.
type LogCreate struct {
	Body        *string   `json:"body,omitempty"`
	CoverImage  *string   `json:"cover_image,omitempty"`
	Description *string   `json:"description,omitempty"`
	Slug        string    `json:"slug"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
}

// LogIndex defines model for LogIndex.
type LogIndex struct {
	Items []LogSummary `json:"items"`
	Total int          `json:"total"`
}

// LogPatch defines model for LogPatch.
type LogPatch struct {
	Body        *string   `json:"body,omitempty"`
	CoverImage  *string   `json:"cover_image,omitempty"`
	Description *string   `json:"description,omitempty"`
	Slug        *string   `json:"slug,omitempty"`
	State       *LogState `json:"state,omitempty"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
}

// LogState defines model for LogState.
type LogState string

// LogSummary defines model for LogSummary.
type LogSummary struct {
	CoverImage  *string   `json:"cover_image,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	ReadingTime *int      `json:"reading_time,omitempty"`
	Slug        string    `json:"slug"`
	State       LogState  `json:"state"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Media defines model for Media.
type Media struct {
	ContentType string     `json:"content_type"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	Key         string     `json:"key"`
	State       MediaState `json:"state"`

	// Url Public CDN URL; bytes never pass through custodian.
	Url string `json:"url"`
}

// MediaList defines model for MediaList.
type MediaList struct {
	Items []Media `json:"items"`
	Total int     `json:"total"`
}

// MediaReservation defines model for MediaReservation.
type MediaReservation struct {
	ExpiresAt time.Time `json:"expires_at"`
	Key       string    `json:"key"`
	UploadUrl string    `json:"upload_url"`
	Url       string    `json:"url"`
}

// MediaReserve defines model for MediaReserve.
type MediaReserve struct {
	ContentType string `json:"content_type"`

	// Key Author-chosen kebab-case key; omit for a random one.
	Key *string `json:"key,omitempty"`
}

// MediaState defines model for MediaState.
type MediaState string

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	Code   string        `json:"code"`
	Detail *string       `json:"detail,omitempty"`
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`
	Title  string        `json:"title"`
	Type   *string       `json:"type,omitempty"`
}

// Profile defines model for Profile.
type Profile struct {
	// Body Opaque JSON; custodian does not validate its shape.
	Body ProfileBody `json:"body"`
	Key  string      `json:"key"`
}

// ProfileBody Opaque JSON; custodian does not validate its shape.
type ProfileBody map[string]interface{}

// Limit defines model for Limit.
type Limit = int

// MediaKey defines model for MediaKey.
type MediaKey = string

// Offset defines model for Offset.
type Offset = int

// ProfileKey defines model for ProfileKey.
type ProfileKey = string

// Slug defines model for Slug.
type Slug = string

// Source defines model for Source.
type Source = IntegrationSource

// StateFilter defines model for StateFilter.
type StateFilter = LogState

// Tag defines model for Tag.
type Tag = string

// ListAdminLogsParams defines parameters for ListAdminLogs.
type ListAdminLogsParams struct {
	Limit  *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset      `form:"offset,omitempty" json:"offset,omitempty"`
	Tag    *Tag         `form:"tag,omitempty" json:"tag,omitempty"`
	State  *StateFilter `form:"state,omitempty" json:"state,omitempty"`
}

// ListMediaParams defines parameters for ListMedia.
type ListMediaParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListPublicLogsParams defines parameters for ListPublicLogs.
type ListPublicLogsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Tag    *Tag    `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateLogJSONRequestBody defines body for CreateLog for application/json ContentType.
type CreateLogJSONRequestBody = LogCreate

// PatchLogJSONRequestBody defines body for PatchLog for application/json ContentType.
type PatchLogJSONRequestBody = LogPatch

// ReserveMediaJSONRequestBody defines body for ReserveMedia for application/json ContentType.
type ReserveMediaJSONRequestBody = MediaReserve

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = ProfileBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Force an immediate poll of a source and return the fresh record.
	// (POST /admin/v1/integrations/{source}/refresh)
	RefreshIntegration(w http.ResponseWriter, r *http.Request, source Source)
	// Index of logs in any state (drafts included).
	// (GET /admin/v1/logs)
	ListAdminLogs(w http.ResponseWriter, r *http.Request, params ListAdminLogsParams)
	// Create a log as an unlisted draft.
	// (POST /admin/v1/logs)
	CreateLog(w http.ResponseWriter, r *http.Request)
	// Delete a log entirely.
	// (DELETE /admin/v1/logs/{slug})
	DeleteLog(w http.ResponseWriter, r *http.Request, slug Slug)
	// Partially update a log (state, slug, body, metadata).
	// (PATCH /admin/v1/logs/{slug})
	PatchLog(w http.ResponseWriter, r *http.Request, slug Slug)
	// List and search media records.
	// (GET /admin/v1/media)
	ListMedia(w http.ResponseWriter, r *http.Request, params ListMediaParams)
	// Reserve a media record and return a presigned upload URL.
	// (POST /admin/v1/media)
	ReserveMedia(w http.ResponseWriter, r *http.Request)
	// Delete a media record.
	// (DELETE /admin/v1/media/{key})
	DeleteMedia(w http.ResponseWriter, r *http.Request, key MediaKey)
	// Fetch a single media record.
	// (GET /admin/v1/media/{key})
	GetMedia(w http.ResponseWriter, r *http.Request, key MediaKey)
	// Confirm an upload; custodian HEADs S3 before flipping to available.
	// (POST /admin/v1/media/{key}/confirm)
	ConfirmMedia(w http.ResponseWriter, r *http.Request, key MediaKey)
	// Upsert a profile record with an opaque JSON body (not validated).
	// (PUT /admin/v1/profile/{key})
	PutProfile(w http.ResponseWriter, r *http.Request, key ProfileKey)
	// The latest polled record for a source, with its fetch timestamp.
	// (GET /v1/integrations/{source})
	GetPublicIntegration(w http.ResponseWriter, r *http.Request, source Source)
	// Paginated index of listed logs (bodies omitted).
	// (GET /v1/logs)
	ListPublicLogs(w http.ResponseWriter, r *http.Request, params ListPublicLogsParams)
	// A single log by slug, including its body, in any state.
	// (GET /v1/logs/{slug})
	GetPublicLog(w http.ResponseWriter, r *http.Request, slug Slug)
	// A profile record by key.
	// (GET /v1/profile/{key})
	GetPublicProfile(w http.ResponseWriter, r *http.Request, key ProfileKey)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Force an immediate poll of a source and return the fresh record.
// (POST /admin/v1/integrations/{source}/refresh)
func (_ Unimplemented) RefreshIntegration(w http.ResponseWriter, r *http.Request, source Source) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Index of logs in any state (drafts included).
// (GET /admin/v1/logs)
func (_ Unimplemented) ListAdminLogs(w http.ResponseWriter, r *http.Request, params ListAdminLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a log as an unlisted draft.
// (POST /admin/v1/logs)
func (_ Unimplemented) CreateLog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a log entirely.
// (DELETE /admin/v1/logs/{slug})
func (_ Unimplemented) DeleteLog(w http.ResponseWriter, r *http.Request, slug Slug) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Partially update a log (state, slug, body, metadata).
// (PATCH /admin/v1/logs/{slug})
func (_ Unimplemented) PatchLog(w http.ResponseWriter, r *http.Request, slug Slug) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List and search media records.
// (GET /admin/v1/media)
func (_ Unimplemented) ListMedia(w http.ResponseWriter, r *http.Request, params ListMediaParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reserve a media record and return a presigned upload URL.
// (POST /admin/v1/media)
func (_ Unimplemented) ReserveMedia(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a media record.
// (DELETE /admin/v1/media/{key})
func (_ Unimplemented) DeleteMedia(w http.ResponseWriter, r *http.Request, key MediaKey) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a single media record.
// (GET /admin/v1/media/{key})
func (_ Unimplemented) GetMedia(w http.ResponseWriter, r *http.Request, key MediaKey) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm an upload; custodian HEADs S3 before flipping to available.
// (POST /admin/v1/media/{key}/confirm)
func (_ Unimplemented) ConfirmMedia(w http.ResponseWriter, r *http.Request, key MediaKey) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upsert a profile record with an opaque JSON body (not validated).
// (PUT /admin/v1/profile/{key})
func (_ Unimplemented) PutProfile(w http.ResponseWriter, r *http.Request, key ProfileKey) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The latest polled record for a source, with its fetch timestamp.
// (GET /v1/integrations/{source})
func (_ Unimplemented) GetPublicIntegration(w http.ResponseWriter, r *http.Request, source Source) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Paginated index of listed logs (bodies omitted).
// (GET /v1/logs)
func (_ Unimplemented) ListPublicLogs(w http.ResponseWriter, r *http.Request, params ListPublicLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// A single log by slug, including its body, in any state.
// (GET /v1/logs/{slug})
func (_ Unimplemented) GetPublicLog(w http.ResponseWriter, r *http.Request, slug Slug) {
	w.WriteHeader(http.StatusNotImplemented)
}

// A profile record by key.
// (GET /v1/profile/{key})
func (_ Unimplemented) GetPublicProfile(w http.ResponseWriter, r *http.Request, key ProfileKey) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RefreshIntegration operation middleware
func (siw *ServerInterfaceWrapper) RefreshIntegration(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "source" -------------
	var source Source

	err = runtime.BindStyledParameterWithOptions("simple", "source", chi.URLParam(r, "source"), &source, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshIntegration(w, r, source)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminLogs operation middleware
func (siw *ServerInterfaceWrapper) ListAdminLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLog operation middleware
func (siw *ServerInterfaceWrapper) CreateLog(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLog operation middleware
func (siw *ServerInterfaceWrapper) DeleteLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLog(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchLog operation middleware
func (siw *ServerInterfaceWrapper) PatchLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchLog(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMedia operation middleware
func (siw *ServerInterfaceWrapper) ListMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMediaParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMedia(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReserveMedia operation middleware
func (siw *ServerInterfaceWrapper) ReserveMedia(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReserveMedia(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMedia operation middleware
func (siw *ServerInterfaceWrapper) DeleteMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key MediaKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMedia(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMedia operation middleware
func (siw *ServerInterfaceWrapper) GetMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key MediaKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMedia(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmMedia operation middleware
func (siw *ServerInterfaceWrapper) ConfirmMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key MediaKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmMedia(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutProfile operation middleware
func (siw *ServerInterfaceWrapper) PutProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key ProfileKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutProfile(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicIntegration operation middleware
func (siw *ServerInterfaceWrapper) GetPublicIntegration(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "source" -------------
	var source Source

	err = runtime.BindStyledParameterWithOptions("simple", "source", chi.URLParam(r, "source"), &source, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicIntegration(w, r, source)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPublicLogs operation middleware
func (siw *ServerInterfaceWrapper) ListPublicLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPublicLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicLog operation middleware
func (siw *ServerInterfaceWrapper) GetPublicLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicLog(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicProfile operation middleware
func (siw *ServerInterfaceWrapper) GetPublicProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key ProfileKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicProfile(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/integrations/{source}/refresh", wrapper.RefreshIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/logs", wrapper.ListAdminLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/logs", wrapper.CreateLog)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/v1/logs/{slug}", wrapper.DeleteLog)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/v1/logs/{slug}", wrapper.PatchLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/media", wrapper.ListMedia)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/media", wrapper.ReserveMedia)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/v1/media/{key}", wrapper.DeleteMedia)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/v1/media/{key}", wrapper.GetMedia)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/v1/media/{key}/confirm", wrapper.ConfirmMedia)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/v1/profile/{key}", wrapper.PutProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/integrations/{source}", wrapper.GetPublicIntegration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/logs", wrapper.ListPublicLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/logs/{slug}", wrapper.GetPublicLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/profile/{key}", wrapper.GetPublicProfile)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW3PbuhH+KztoH+yWlpycdDpHfvLJrWnVE4+dTB8ynhyIXJI4JgEGAJ1wPPrvHVx4",
	"kQVaUmKraqdvFgnuLvbbGz7SdyQWZSU4cq3I7I5UVNISNUr7a85Kps0fjJMZ+VKjbEhEOC2RzEhhb0ZE",
	"xTmW1KxKMKV1ocns+WlESvqNlXVJZs9OzS/G/a+I6KYyzzOuMUNJlsuI/BMTRv+BTaerojrvVd2g0Svx",
	"S80kJmSmZY1DxV6i0pLxzAp8n6YKR00X7m7Q9qGxp0FjL6RIWYGPae5VUWcjwpS5taM0UcsYx+S5mw9J",
	"/KPElMzIH6Z9bEzdXTV9ZxwhqWaCezVWo6Ya37BCoxzzuTJLyLZq5iKzMq30DzQbk6ppRh5yxtLsU1WC",
	"K7QRfSHFosDS/BkLrpHbGKFVVbDYbmpauRV//l0Jbu5tZ28r12pMUMWSVUYcmZFzDpdvXsLPL/7yV/DC",
	"IRFxXSLXE7s/L8ToeMOwSF5LKawfKykqlJo521NzL7DJiJSoFM0wHA09zp+8iP6B6y7AxeJ3jLURNkB4",
	"3YaEausLmiTMrKDFxeC+C6TV7c+pRqWhEkWBCdgoOANeFwV8zZEDFzpnPIOcKlggchALhfIWkwkJ2Jai",
	"jnNMPlPtcnao6F9GXFwrLRJGORRUafDrz6CSqJBrwFvkTrHZCTBlTTG6UiFLI9ZsEU80K7E3oPe06lJr",
	"9yQZAtFl4WBHG8Dosxq5KU6fiNJISxKRjOm8Xgye7+2di2wdxIVImmAcxeIW5WdWhmMpIrFEqjv3b+ex",
	"FZACMiXShPHss32+X9AV3MhVwNCjrqRsXUkiouqFZroIb07TzHqHaSxVeIW7QKWkjf09Kquukh0ddT8+",
	"XNV3GqKueFrkVnBY0RWKoLnIXtrljxgHmzAdR2w/ADzkzBEfveMJflt3UWdL98emWKvLksomaK3QtAiF",
	"+D1z3brIqxyx94LqOD8ISA80CZdhv1215rZFtGBKo+mJNfd/jtTRFtk1n/+/ah541dylXNqTSAhjOyx+",
	"dusfCWT8VjGJaqdnbrD5flTt5jpca1msT1EX9aJgMbx89St8vJyfwaLRqIDjLUqoqFKgcynqLO8nrclG",
	"WNx5qEXDqI1WHbrivlFU5kzpH63QDt4nLc5WxSWaKXZkiH5M3OuqEDT57LFcvx28HsRnIKkFaWDohp3i",
	"d6SM39K901KtcyFP4lwo5HCDC7o4ialCuMHmDETJNKRCAgVJeSJKEBw3B+CKKaM7WWsNFXJTZElE6C1l",
	"BV2sjA/9RgaHyvsuSHB9i1faSIKSxjnjeGJKub2A5tgH5plJuCVoysIo2ye3T4LBITOQCSZPaxVuKg/0",
	"gTDK97NnUJlrZctAEkbEkyzjE86G07h5+BezdDR3gklgpT9gzy9e+/bn3/cV/VIj/P3q/a9ng+NpIkxZ",
	"FRpuacFM5gPTClROKwycfA0sGNeS6ebK7NG7AqlEaTKmIyrMQ+5yLyTXunLEBOOpWI/HDznC+cU70DnV",
	"cINYmSKPUBW0yaSoeTKBc6hcXzDBCqqWKY0Rjn6b3j6b/um3CGpOa50j1yw2ZTyCt68/nAheNBHENM7R",
	"xPcxUJ4A5UCTkvGhEHuhFeWsP7knL62LAl5efnx1PIEPOVMdg2KO8MbanPLEPiQkJuCO1yBS0LLW+RnY",
	"GiXBhLJVq6wxseCqLlFCXDATQJAhR2nASKUogelJN03MSIcdicgtSuWcdzp5Njk1ASIq5LRiZEZ+spci",
	"y7tZnPoNsv44r6Z3zsrlVGIqUblpXrgeZ2LKLnuXkBm5dAuGzEy0QtV+CudDv2Ta8hDX9wix56enD5Bh",
	"u5FgQ/sCRJiJM7uPomnpoIE/QGIsZDJxpc6TsWF93QYGtFufINYbw9T4dG12rdrxnbwRJjYoB1aWpu5r",
	"tOaYaKFt5JjokKhryW10WbM7C9up9xMZ4kmujRU91oVwk3GGAUTNLHNuVs7Nql3BdLz8Mtq40NPgW6z8",
	"QLNtlg2J3ieNpe5IHmJUoaKZze5CZOCAZahs6Lw4fbZD2Dx1qNkteEMVMA6UN44DhaNE0lSbi3FRJ5gc",
	"D+PKxs71MhqpB47QmYv2xQAq3Tamx3K+54yWq23SNLjlGurPHlPxWOXwJwTjSQ/0zzsB/eL58wMKDOde",
	"oDaCqelG0PIPYAMjEA1r1WV6Zw68S9fRC3TD62qkvLLXXaTs2DDMWTqQ4i/WBwinZB+l22nybjPjgcSi",
	"CSdOy4+t+sPSZj/ojifJN8fnbZVup/tIN0+TWEcfYZybcdV0wriW0oxdJvKOvysRnzZCLqjUjBZF43fg",
	"Y+XIFt3Imh2BmfIjKFHThGp6vCnXypYTGm3ljlbYRxsPvQT98uAr0Kfs0j0v82Cbtg7045PaQ5kwFtkR",
	"TiGVcX5ff4+2Q3a80Xpyo4X3KXJ/hUTZc7tdo6pGioHsl0Twlencvk9lGccEHG0EHy/n1uP+nPjxcn6A",
	"xcG7GehKRAyHfRrcWShk1ivE9O4Gmy268fcVi+4TmYPtyUOfhpMsWD/fon58jzxyiRtLjNUt23h/cUDx",
	"/gZ1nJtDLeNZgRsBGgvpaSx4ymQ5TlC8dAv+a3Hk4utJx/GGUD2kKuadbc8MtkQNecW/vT5/peDqJ1hg",
	"KiRCWrCqYjwDLaDb4UbwK8d29hWtqgOoX9S6pWl3xXzwDd1TDdUrJPB+5+rWK6OztUJphmvv5v1RXx+t",
	"ZtvlhppdT6ccRE9W2yEZjoYU9SpH4UX40BkjN0fH5reo3bvG/wFWs3DfuK2zmXBU0gYWCFhWujlZ1PrE",
	"f4l2/ANod3AOdHtC1at1r8gcBH5iY1q5z+FAsxKVpmW1gcnchsN0EB4UiXmIrOQP4nxBM8btcZx1hKLj",
	"iiyveLQQCUNl347qMJM4wHPAGj2cmI/JGu2Fs7AviXp+cB+TWAfReTtkGfAXjScaHLlr2q9JP0c7DFng",
	"caTWOvDDWD1aH/7PdMRAI9w7fvda4qKBG2xGGp7tufK2dfK99/u0xBMhWcb4mXuTSt2JOWXfQGGBsXZc",
	"mn8FOvHfW8zI1ILg9d11/2hhAsNUP/+7tWNwaaV6D6674W55vfx3AAAA//8g9PbR6DEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
