// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for IntegrationSource.
const (
	Github IntegrationSource = "github"
	Steam  IntegrationSource = "steam"
)

// Defines values for LogState.
const (
	Listed   LogState = "listed"
	Unlisted LogState = "unlisted"
)

// Defines values for MediaState.
const (
	Available MediaState = "available"
	Pending   MediaState = "pending"
)

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Integration defines model for Integration.
type Integration struct {
	// Data Latest polled state; null when nothing has been observed.
	Data *map[string]interface{} `json:"data,omitempty"`

	// FetchedAt When custodian last fetched; present even when data is null.
	FetchedAt time.Time         `json:"fetched_at"`
	Source    IntegrationSource `json:"source"`
}

// IntegrationSource defines model for IntegrationSource.
type IntegrationSource string

// Log defines model for Log.
type Log struct {
	Body        string    `json:"body"`
	CoverImage  *string   `json:"cover_image,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	ReadingTime *int      `json:"reading_time,omitempty"`
	Slug        string    `json:"slug"`
	State       LogState  `json:"state"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// LogCreate defines model for LogCreate.
type LogCreate struct {
	Body        *string   `json:"body,omitempty"`
	CoverImage  *string   `json:"cover_image,omitempty"`
	Description *string   `json:"description,omitempty"`
	Slug        string    `json:"slug"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
}

// LogIndex defines model for LogIndex.
type LogIndex struct {
	Items []LogSummary `json:"items"`
	Total int          `json:"total"`
}

// LogPatch defines model for LogPatch.
type LogPatch struct {
	Body        *string   `json:"body,omitempty"`
	CoverImage  *string   `json:"cover_image,omitempty"`
	Description *string   `json:"description,omitempty"`
	Slug        *string   `json:"slug,omitempty"`
	State       *LogState `json:"state,omitempty"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       *string   `json:"title,omitempty"`
}

// LogState defines model for LogState.
type LogState string

// LogSummary defines model for LogSummary.
type LogSummary struct {
	CoverImage  *string   `json:"cover_image,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	ReadingTime *int      `json:"reading_time,omitempty"`
	Slug        string    `json:"slug"`
	State       LogState  `json:"state"`
	Subtitle    *string   `json:"subtitle,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Media defines model for Media.
type Media struct {
	ContentType string     `json:"content_type"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	Key         string     `json:"key"`
	State       MediaState `json:"state"`

	// Url Public CDN URL; bytes never pass through custodian.
	Url string `json:"url"`
}

// MediaList defines model for MediaList.
type MediaList struct {
	Items []Media `json:"items"`
	Total int     `json:"total"`
}

// MediaReservation defines model for MediaReservation.
type MediaReservation struct {
	ExpiresAt time.Time `json:"expires_at"`
	Key       string    `json:"key"`
	UploadUrl string    `json:"upload_url"`
	Url       string    `json:"url"`
}

// MediaReserve defines model for MediaReserve.
type MediaReserve struct {
	ContentType string `json:"content_type"`

	// Key Author-chosen kebab-case key; omit for a random one.
	Key *string `json:"key,omitempty"`
}

// MediaState defines model for MediaState.
type MediaState string

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	Code   string        `json:"code"`
	Detail *string       `json:"detail,omitempty"`
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`
	Title  string        `json:"title"`
	Type   *string       `json:"type,omitempty"`
}

// Profile defines model for Profile.
type Profile struct {
	// Body Opaque JSON; custodian does not validate its shape.
	Body ProfileBody `json:"body"`
	Key  string      `json:"key"`
}

// ProfileBody Opaque JSON; custodian does not validate its shape.
type ProfileBody map[string]interface{}

// Limit defines model for Limit.
type Limit = int

// MediaKey defines model for MediaKey.
type MediaKey = string

// Offset defines model for Offset.
type Offset = int

// ProfileKey defines model for ProfileKey.
type ProfileKey = string

// Slug defines model for Slug.
type Slug = string

// Source defines model for Source.
type Source = IntegrationSource

// StateFilter defines model for StateFilter.
type StateFilter = LogState

// Tag defines model for Tag.
type Tag = string

// ListAdminLogsParams defines parameters for ListAdminLogs.
type ListAdminLogsParams struct {
	Limit  *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset      `form:"offset,omitempty" json:"offset,omitempty"`
	Tag    *Tag         `form:"tag,omitempty" json:"tag,omitempty"`
	State  *StateFilter `form:"state,omitempty" json:"state,omitempty"`
}

// ListMediaParams defines parameters for ListMedia.
type ListMediaParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListPublicLogsParams defines parameters for ListPublicLogs.
type ListPublicLogsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Tag    *Tag    `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateLogJSONRequestBody defines body for CreateLog for application/json ContentType.
type CreateLogJSONRequestBody = LogCreate

// PatchLogJSONRequestBody defines body for PatchLog for application/json ContentType.
type PatchLogJSONRequestBody = LogPatch

// ReserveMediaJSONRequestBody defines body for ReserveMedia for application/json ContentType.
type ReserveMediaJSONRequestBody = MediaReserve

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = ProfileBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RefreshIntegration request
	RefreshIntegration(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAdminLogs request
	ListAdminLogs(ctx context.Context, params *ListAdminLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateLogWithBody request with any body
	CreateLogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateLog(ctx context.Context, body CreateLogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteLog request
	DeleteLog(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchLogWithBody request with any body
	PatchLogWithBody(ctx context.Context, slug Slug, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchLog(ctx context.Context, slug Slug, body PatchLogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListMedia request
	ListMedia(ctx context.Context, params *ListMediaParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReserveMediaWithBody request with any body
	ReserveMediaWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReserveMedia(ctx context.Context, body ReserveMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMedia request
	DeleteMedia(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMedia request
	GetMedia(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfirmMedia request
	ConfirmMedia(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutProfileWithBody request with any body
	PutProfileWithBody(ctx context.Context, key ProfileKey, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutProfile(ctx context.Context, key ProfileKey, body PutProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicIntegration request
	GetPublicIntegration(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPublicLogs request
	ListPublicLogs(ctx context.Context, params *ListPublicLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicLog request
	GetPublicLog(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicProfile request
	GetPublicProfile(ctx context.Context, key ProfileKey, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RefreshIntegration(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshIntegrationRequest(c.Server, source)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListAdminLogs(ctx context.Context, params *ListAdminLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAdminLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateLogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateLogRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateLog(ctx context.Context, body CreateLogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateLogRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteLog(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteLogRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchLogWithBody(ctx context.Context, slug Slug, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchLogRequestWithBody(c.Server, slug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchLog(ctx context.Context, slug Slug, body PatchLogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchLogRequest(c.Server, slug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMedia(ctx context.Context, params *ListMediaParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMediaRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReserveMediaWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReserveMediaRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReserveMedia(ctx context.Context, body ReserveMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReserveMediaRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteMedia(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMediaRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMedia(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMediaRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmMedia(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmMediaRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutProfileWithBody(ctx context.Context, key ProfileKey, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutProfileRequestWithBody(c.Server, key, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutProfile(ctx context.Context, key ProfileKey, body PutProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutProfileRequest(c.Server, key, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicIntegration(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicIntegrationRequest(c.Server, source)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPublicLogs(ctx context.Context, params *ListPublicLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPublicLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicLog(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicLogRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicProfile(ctx context.Context, key ProfileKey, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicProfileRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRefreshIntegrationRequest generates requests for RefreshIntegration
func NewRefreshIntegrationRequest(server string, source Source) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "source", runtime.ParamLocationPath, source)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/integrations/%s/refresh", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListAdminLogsRequest generates requests for ListAdminLogs
func NewListAdminLogsRequest(server string, params *ListAdminLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tag != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tag", runtime.ParamLocationQuery, *params.Tag); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, *params.State); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateLogRequest calls the generic CreateLog builder with application/json body
func NewCreateLogRequest(server string, body CreateLogJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateLogRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateLogRequestWithBody generates requests for CreateLog with any type of body
func NewCreateLogRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteLogRequest generates requests for DeleteLog
func NewDeleteLogRequest(server string, slug Slug) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/logs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchLogRequest calls the generic PatchLog builder with application/json body
func NewPatchLogRequest(server string, slug Slug, body PatchLogJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchLogRequestWithBody(server, slug, "application/json", bodyReader)
}

// NewPatchLogRequestWithBody generates requests for PatchLog with any type of body
func NewPatchLogRequestWithBody(server string, slug Slug, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/logs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListMediaRequest generates requests for ListMedia
func NewListMediaRequest(server string, params *ListMediaParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/media")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "q", runtime.ParamLocationQuery, *params.Q); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReserveMediaRequest calls the generic ReserveMedia builder with application/json body
func NewReserveMediaRequest(server string, body ReserveMediaJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReserveMediaRequestWithBody(server, "application/json", bodyReader)
}

// NewReserveMediaRequestWithBody generates requests for ReserveMedia with any type of body
func NewReserveMediaRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/media")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteMediaRequest generates requests for DeleteMedia
func NewDeleteMediaRequest(server string, key MediaKey) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "key", runtime.ParamLocationPath, key)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/media/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMediaRequest generates requests for GetMedia
func NewGetMediaRequest(server string, key MediaKey) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "key", runtime.ParamLocationPath, key)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/media/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewConfirmMediaRequest generates requests for ConfirmMedia
func NewConfirmMediaRequest(server string, key MediaKey) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "key", runtime.ParamLocationPath, key)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/media/%s/confirm", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutProfileRequest calls the generic PutProfile builder with application/json body
func NewPutProfileRequest(server string, key ProfileKey, body PutProfileJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutProfileRequestWithBody(server, key, "application/json", bodyReader)
}

// NewPutProfileRequestWithBody generates requests for PutProfile with any type of body
func NewPutProfileRequestWithBody(server string, key ProfileKey, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "key", runtime.ParamLocationPath, key)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/profile/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPublicIntegrationRequest generates requests for GetPublicIntegration
func NewGetPublicIntegrationRequest(server string, source Source) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "source", runtime.ParamLocationPath, source)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/integrations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPublicLogsRequest generates requests for ListPublicLogs
func NewListPublicLogsRequest(server string, params *ListPublicLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tag != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tag", runtime.ParamLocationQuery, *params.Tag); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicLogRequest generates requests for GetPublicLog
func NewGetPublicLogRequest(server string, slug Slug) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/logs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicProfileRequest generates requests for GetPublicProfile
func NewGetPublicProfileRequest(server string, key ProfileKey) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "key", runtime.ParamLocationPath, key)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/profile/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RefreshIntegrationWithResponse request
	RefreshIntegrationWithResponse(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*RefreshIntegrationResponse, error)

	// ListAdminLogsWithResponse request
	ListAdminLogsWithResponse(ctx context.Context, params *ListAdminLogsParams, reqEditors ...RequestEditorFn) (*ListAdminLogsResponse, error)

	// CreateLogWithBodyWithResponse request with any body
	CreateLogWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateLogResponse, error)

	CreateLogWithResponse(ctx context.Context, body CreateLogJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateLogResponse, error)

	// DeleteLogWithResponse request
	DeleteLogWithResponse(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*DeleteLogResponse, error)

	// PatchLogWithBodyWithResponse request with any body
	PatchLogWithBodyWithResponse(ctx context.Context, slug Slug, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchLogResponse, error)

	PatchLogWithResponse(ctx context.Context, slug Slug, body PatchLogJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchLogResponse, error)

	// ListMediaWithResponse request
	ListMediaWithResponse(ctx context.Context, params *ListMediaParams, reqEditors ...RequestEditorFn) (*ListMediaResponse, error)

	// ReserveMediaWithBodyWithResponse request with any body
	ReserveMediaWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReserveMediaResponse, error)

	ReserveMediaWithResponse(ctx context.Context, body ReserveMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*ReserveMediaResponse, error)

	// DeleteMediaWithResponse request
	DeleteMediaWithResponse(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*DeleteMediaResponse, error)

	// GetMediaWithResponse request
	GetMediaWithResponse(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*GetMediaResponse, error)

	// ConfirmMediaWithResponse request
	ConfirmMediaWithResponse(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*ConfirmMediaResponse, error)

	// PutProfileWithBodyWithResponse request with any body
	PutProfileWithBodyWithResponse(ctx context.Context, key ProfileKey, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutProfileResponse, error)

	PutProfileWithResponse(ctx context.Context, key ProfileKey, body PutProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*PutProfileResponse, error)

	// GetPublicIntegrationWithResponse request
	GetPublicIntegrationWithResponse(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*GetPublicIntegrationResponse, error)

	// ListPublicLogsWithResponse request
	ListPublicLogsWithResponse(ctx context.Context, params *ListPublicLogsParams, reqEditors ...RequestEditorFn) (*ListPublicLogsResponse, error)

	// GetPublicLogWithResponse request
	GetPublicLogWithResponse(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*GetPublicLogResponse, error)

	// GetPublicProfileWithResponse request
	GetPublicProfileWithResponse(ctx context.Context, key ProfileKey, reqEditors ...RequestEditorFn) (*GetPublicProfileResponse, error)
}

type RefreshIntegrationResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Integration
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r RefreshIntegrationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RefreshIntegrationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListAdminLogsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *LogIndex
	ApplicationproblemJSON401     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r ListAdminLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAdminLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateLogResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON201                       *Log
	ApplicationproblemJSON409     *Problem
	ApplicationproblemJSON422     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r CreateLogResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateLogResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteLogResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r DeleteLogResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteLogResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchLogResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Log
	ApplicationproblemJSON409     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r PatchLogResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchLogResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListMediaResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *MediaList
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r ListMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReserveMediaResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON201                       *MediaReservation
	ApplicationproblemJSON409     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r ReserveMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReserveMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteMediaResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r DeleteMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMediaResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Media
	ApplicationproblemJSON404     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r GetMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConfirmMediaResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Media
	ApplicationproblemJSON409     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r ConfirmMediaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfirmMediaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutProfileResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Profile
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r PutProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPublicIntegrationResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Integration
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r GetPublicIntegrationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicIntegrationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPublicLogsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *LogIndex
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r ListPublicLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPublicLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPublicLogResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Log
	ApplicationproblemJSON404     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r GetPublicLogResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicLogResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPublicProfileResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Profile
	ApplicationproblemJSON404     *Problem
	ApplicationproblemJSONDefault *Problem
}

// Status returns HTTPResponse.Status
func (r GetPublicProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RefreshIntegrationWithResponse request returning *RefreshIntegrationResponse
func (c *ClientWithResponses) RefreshIntegrationWithResponse(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*RefreshIntegrationResponse, error) {
	rsp, err := c.RefreshIntegration(ctx, source, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshIntegrationResponse(rsp)
}

// ListAdminLogsWithResponse request returning *ListAdminLogsResponse
func (c *ClientWithResponses) ListAdminLogsWithResponse(ctx context.Context, params *ListAdminLogsParams, reqEditors ...RequestEditorFn) (*ListAdminLogsResponse, error) {
	rsp, err := c.ListAdminLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAdminLogsResponse(rsp)
}

// CreateLogWithBodyWithResponse request with arbitrary body returning *CreateLogResponse
func (c *ClientWithResponses) CreateLogWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateLogResponse, error) {
	rsp, err := c.CreateLogWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateLogResponse(rsp)
}

func (c *ClientWithResponses) CreateLogWithResponse(ctx context.Context, body CreateLogJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateLogResponse, error) {
	rsp, err := c.CreateLog(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateLogResponse(rsp)
}

// DeleteLogWithResponse request returning *DeleteLogResponse
func (c *ClientWithResponses) DeleteLogWithResponse(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*DeleteLogResponse, error) {
	rsp, err := c.DeleteLog(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteLogResponse(rsp)
}

// PatchLogWithBodyWithResponse request with arbitrary body returning *PatchLogResponse
func (c *ClientWithResponses) PatchLogWithBodyWithResponse(ctx context.Context, slug Slug, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchLogResponse, error) {
	rsp, err := c.PatchLogWithBody(ctx, slug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchLogResponse(rsp)
}

func (c *ClientWithResponses) PatchLogWithResponse(ctx context.Context, slug Slug, body PatchLogJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchLogResponse, error) {
	rsp, err := c.PatchLog(ctx, slug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchLogResponse(rsp)
}

// ListMediaWithResponse request returning *ListMediaResponse
func (c *ClientWithResponses) ListMediaWithResponse(ctx context.Context, params *ListMediaParams, reqEditors ...RequestEditorFn) (*ListMediaResponse, error) {
	rsp, err := c.ListMedia(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMediaResponse(rsp)
}

// ReserveMediaWithBodyWithResponse request with arbitrary body returning *ReserveMediaResponse
func (c *ClientWithResponses) ReserveMediaWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReserveMediaResponse, error) {
	rsp, err := c.ReserveMediaWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReserveMediaResponse(rsp)
}

func (c *ClientWithResponses) ReserveMediaWithResponse(ctx context.Context, body ReserveMediaJSONRequestBody, reqEditors ...RequestEditorFn) (*ReserveMediaResponse, error) {
	rsp, err := c.ReserveMedia(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReserveMediaResponse(rsp)
}

// DeleteMediaWithResponse request returning *DeleteMediaResponse
func (c *ClientWithResponses) DeleteMediaWithResponse(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*DeleteMediaResponse, error) {
	rsp, err := c.DeleteMedia(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMediaResponse(rsp)
}

// GetMediaWithResponse request returning *GetMediaResponse
func (c *ClientWithResponses) GetMediaWithResponse(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*GetMediaResponse, error) {
	rsp, err := c.GetMedia(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMediaResponse(rsp)
}

// ConfirmMediaWithResponse request returning *ConfirmMediaResponse
func (c *ClientWithResponses) ConfirmMediaWithResponse(ctx context.Context, key MediaKey, reqEditors ...RequestEditorFn) (*ConfirmMediaResponse, error) {
	rsp, err := c.ConfirmMedia(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmMediaResponse(rsp)
}

// PutProfileWithBodyWithResponse request with arbitrary body returning *PutProfileResponse
func (c *ClientWithResponses) PutProfileWithBodyWithResponse(ctx context.Context, key ProfileKey, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutProfileResponse, error) {
	rsp, err := c.PutProfileWithBody(ctx, key, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutProfileResponse(rsp)
}

func (c *ClientWithResponses) PutProfileWithResponse(ctx context.Context, key ProfileKey, body PutProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*PutProfileResponse, error) {
	rsp, err := c.PutProfile(ctx, key, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutProfileResponse(rsp)
}

// GetPublicIntegrationWithResponse request returning *GetPublicIntegrationResponse
func (c *ClientWithResponses) GetPublicIntegrationWithResponse(ctx context.Context, source Source, reqEditors ...RequestEditorFn) (*GetPublicIntegrationResponse, error) {
	rsp, err := c.GetPublicIntegration(ctx, source, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicIntegrationResponse(rsp)
}

// ListPublicLogsWithResponse request returning *ListPublicLogsResponse
func (c *ClientWithResponses) ListPublicLogsWithResponse(ctx context.Context, params *ListPublicLogsParams, reqEditors ...RequestEditorFn) (*ListPublicLogsResponse, error) {
	rsp, err := c.ListPublicLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPublicLogsResponse(rsp)
}

// GetPublicLogWithResponse request returning *GetPublicLogResponse
func (c *ClientWithResponses) GetPublicLogWithResponse(ctx context.Context, slug Slug, reqEditors ...RequestEditorFn) (*GetPublicLogResponse, error) {
	rsp, err := c.GetPublicLog(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicLogResponse(rsp)
}

// GetPublicProfileWithResponse request returning *GetPublicProfileResponse
func (c *ClientWithResponses) GetPublicProfileWithResponse(ctx context.Context, key ProfileKey, reqEditors ...RequestEditorFn) (*GetPublicProfileResponse, error) {
	rsp, err := c.GetPublicProfile(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicProfileResponse(rsp)
}

// ParseRefreshIntegrationResponse parses an HTTP response from a RefreshIntegrationWithResponse call
func ParseRefreshIntegrationResponse(rsp *http.Response) (*RefreshIntegrationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RefreshIntegrationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Integration
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListAdminLogsResponse parses an HTTP response from a ListAdminLogsWithResponse call
func ParseListAdminLogsResponse(rsp *http.Response) (*ListAdminLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAdminLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LogIndex
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCreateLogResponse parses an HTTP response from a CreateLogWithResponse call
func ParseCreateLogResponse(rsp *http.Response) (*CreateLogResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateLogResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Log
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteLogResponse parses an HTTP response from a DeleteLogWithResponse call
func ParseDeleteLogResponse(rsp *http.Response) (*DeleteLogResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteLogResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePatchLogResponse parses an HTTP response from a PatchLogWithResponse call
func ParsePatchLogResponse(rsp *http.Response) (*PatchLogResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchLogResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Log
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListMediaResponse parses an HTTP response from a ListMediaWithResponse call
func ParseListMediaResponse(rsp *http.Response) (*ListMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MediaList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseReserveMediaResponse parses an HTTP response from a ReserveMediaWithResponse call
func ParseReserveMediaResponse(rsp *http.Response) (*ReserveMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReserveMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest MediaReservation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteMediaResponse parses an HTTP response from a DeleteMediaWithResponse call
func ParseDeleteMediaResponse(rsp *http.Response) (*DeleteMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetMediaResponse parses an HTTP response from a GetMediaWithResponse call
func ParseGetMediaResponse(rsp *http.Response) (*GetMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Media
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseConfirmMediaResponse parses an HTTP response from a ConfirmMediaWithResponse call
func ParseConfirmMediaResponse(rsp *http.Response) (*ConfirmMediaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfirmMediaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Media
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePutProfileResponse parses an HTTP response from a PutProfileWithResponse call
func ParsePutProfileResponse(rsp *http.Response) (*PutProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Profile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetPublicIntegrationResponse parses an HTTP response from a GetPublicIntegrationWithResponse call
func ParseGetPublicIntegrationResponse(rsp *http.Response) (*GetPublicIntegrationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicIntegrationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Integration
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListPublicLogsResponse parses an HTTP response from a ListPublicLogsWithResponse call
func ParseListPublicLogsResponse(rsp *http.Response) (*ListPublicLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPublicLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LogIndex
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetPublicLogResponse parses an HTTP response from a GetPublicLogWithResponse call
func ParseGetPublicLogResponse(rsp *http.Response) (*GetPublicLogResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicLogResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Log
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetPublicProfileResponse parses an HTTP response from a GetPublicProfileWithResponse call
func ParseGetPublicProfileResponse(rsp *http.Response) (*GetPublicProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Profile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
